name: Build Jekyll site

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Upload generated site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: ${{ github.workspace }}/_site
